version: '3.4'

networks:
  insurance-net:
services:
  insuranceapi:
    networks: 
    - insurance-net
    build: ./InsuranceAPI
    container_name: insurance_api
    ports:
    - 5000:80 
  insurancedb:
    networks: 
    - insurance-net
    image: db
    build: ./InsuranceDB
    container_name: insurance_db
